language: ruby
rvm:
- 2.4.1
install:
- bundle
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: EYa7NHEv+0yfdgaGLQPJgNZCDoy0VGX6pijTsx9y5RBk9j/K4coIb0VYUf5ZvUGSBBsMijIip1K8hgfug4fgm48BZa0gipn7nFsyUnPXSA5cGgvzWgCQou24WTZxyVKE28IiAso3NUmN84wgL5+FLQMCBqxzuw/HSDWQ5kZ1YpTBkYytND5F/gJOjXMnnr0oayeql+a1Ah2YjaxE417bc0CWMxwZfbSgwKmLvjSY78Yi4GtveaR186snUVVE0waAQitV/LmAU6fK6Lw1CVOwsyKGBnImooEXXARo30jvPBvt1OFkLrffUEztWc1zrjkYsluJkCLu4b0uysWHJi7SDjS3nzQp4MhX92YDpNBqFRiySSl803ntEzrqq3EGFAA7tXFA42MIDbAiEAoD6ORISBHgyMNf3lXrwS0p3AHzqidNpCpV8dcUsWepGDqDDaM2WRguSbAlSSKK7Gdi9iesQQ84JqTby9mw7nqAHRJLYNEtt2rN4J6eXD9QDejYLFKTZ8HCBoo3Aaj7EtRj7tDnQyDdrUvwfnPFBeE22iDUvafJISzN2Aug8pE/9rp5tKs4Zo6HUW4IcoACp8f/4MPusIPnnLL/x9ofzjJURQ28gsNlPXlYeDxyQ/hj60u2WHMaayISfJZEa5ZiPasD2YG1vEq418AjAkLu91fdGYuqm9Q=

script: jgd -u https://soerenetler:$PASSWORD@github.com/soerenetler/soerenetler.github.io.git
  -b master -r gh-pages

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false
cache: bundler
notifications:
  email: false
