language: ruby
rvm:
  - 2.4.1

#before_install:
#  - gem update --system
#  - gem install bundler

install:
  - bundle

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - secure: "F3tZT8qzUdIXdT16LNm+VBNkgeB+MWmWZfTQZ8Tz8NDA3v/OgP4aO2HeJRgwDWdmX1zrp7+/q6odcpoENvHWvFDGzdlTm1VmS90FlIDy4og3vbEVNWb1i/Q9hVr9WCgCQj7iND3xXMCwOj8VxL+IVeUEQ1+5duqgYrcTwVMe2V8/eqIc9dexpwqFw/C/NetvQ0nBsm8xHDGYeM8VgXbdlKsvg6vYhn33FwMVrwYoWqqO59SNS01cv+GVoSv3tUcJIrgG2jbdueg28Wf70LTjQfSfgq0wHPbAk0YLfGWtgU2Wc2d9QCCF0FoUXVRYzJEyyTmiI2UE8nsknOnIhja8/Ifi5BBQpagaVtxLuEl/uJUqXUpoUteCmhk1fzMVqR215YvcIxAUoqpGT9D9Kjkvt4yjzAP4p0Toe4SnBaz+Gz+5cTB3fJvC63UVgkrcx6ieXlaSHTxKiMCVtYGb4q5H+AzQ8yJgcvNRm1gwzgjVK2nBZtcj5xqL5Va9dZJp2W5WRVveQFVTCsbs7UkzI2oO8yLfw9kJxdNYt0i9KBKXszuCfAZdg4etxOrgsU/haUq0PieSEuEZ+Iw6AuwPHMvzyBL8VHmKp/q7DuBdyN2WMv6om4hrFsIO4+vS37JRkV7k9HLoD1RegUfvnAEMsO3sARIcRHBjQLvvWzut5ufC3Is="

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: jgd -u http://soerenetler:$PASSWORD@github.com/soerenetler/soerenetler.github.io.git -b master -r gh-pages

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false