language: ruby
rvm:
  - 2.4.1

before_install:
  - gem update --system
  - gem install bundler

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: jgd -u http://soerenetler:$PASSWORD@github.com/soerenetler/soerenetler.github.io.git -b master -r gh-pages

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - secure: "vfp5DLyCFvNoMHu4YWMMB+kOGzsaVITsXkRtk3B1I//HyelutHYNVcl7jg0wmto3LOt8bgnVZDWqFeYh1qgKy8yx/tB5favp31ufgkMBIrQdNqnVcpyfN3hqUgCmk+onUsgSJUmzKHkNIvNYO0k8eQS8v8lgrnOTeJGTH5OGQAoeWP6ITuBApEKcQ9/LwivrDjgnxVFfx+rBjeWDK2FAvb9UrnZWxPlpO+0mZJl87sqeqOcn8M47rdh8Pljtc5PMQQu+hKu4vMSqTcjVPwGE/iQodc3cBPTCK7ZtK9Lv6pC/Pp/Xq6mQDnfb5o1R5C4r1M60ia+b5iKKurKXR9di/CEg88Fx78XwW6klNfI+XW6NHJm07BWDEJtQnDUN1EiBanOxaDPbAbtOh6WQ4mEJnbCJV7u4lD/X98Wp2ktLeAdM6zh5w+/49qiS7fjrQFVFqVNY4FaGyP86iUDJoEke5ev0sxfzXXlla2exhI7NYRzBWvqg4gnS0So8xS2lwCIxAhYofU7p1LER/Y35x38AXrreQziZUeeeh+/BmteC1NVldqvQzpN5zyidCK3PPmr6iZ/8neoArIbwjbfDlc5s1qcwnJkNwHREnemUaYJqJ3h1jJUyNHCcmgtDCrlOXaj/kqSCA2e/yIudYYCpWi5MwUumP6iEises6G00pduSe5o="

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false